title: Soars Science
description: 学术播客
url: https://loongfee.github.io/soars-podcast
baseurl: /soars-podcast

theme: minima  # 或其他支持的主题

# RSS Feed 设置
podcast:
  title: Soars Science
  description: 学术播客
  url: https://loongfee.github.io/soars-podcast
  author: Soars
  email: loongfee@email.com
  category: Technology
  subcategory: Software
  explicit: "no"
  language: zh-CN
  explicit: "no"

# 添加插件支持
plugins:
  - jekyll-feed
  - jekyll-seo-tag